{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "lana.hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lana.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "lana.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lana.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare ">=1.23-0" (include "lana.capabilities.kubeVersion" .) }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- else }}
        targetAverageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare ">=1.23-0" (include "lana.capabilities.kubeVersion" .) }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- else }}
        targetAverageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
{{- end }}
