{{- if include "lana.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lana.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "lana.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
