{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lana.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.serviceMonitor.namespace | quote }}
  labels: {{- include "lana.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels: {{- include "lana.selectorLabels" . | nindent 6 }}
    {{- with .Values.serviceMonitor.selector }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  endpoints:
    - port: http
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings: {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
{{- end }}
